apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: sechay-website-monitor
  namespace: monitoring
  labels:
    release: monitoring
spec:
  selector: 
    matchLabels: 
      app: sechay-website
  namespaceSelector:
    matchNames: 
      - enterprise-website
  endpoints:
  - port: metrics
    path: /metrics
    interval: 15s


